name: Run Java Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with Maven
        if: exists('pom.xml')
        run: mvn --batch-mode --update-snapshots test

      - name: Run tests with Gradle
        if: exists('build.gradle') || exists('build.gradle.kts')
        run: ./gradlew test
