name: Run Java Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

    
      - name: List project files (for debugging)
        run: ls -R

  
      - name: Run tests
        run: |
          if [ -f "pom.xml" ]; then
            echo "Maven project detected. Running tests..."
            mvn --batch-mode --update-snapshots test
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "Gradle project detected. Running tests..."
            chmod +x ./gradlew
            ./gradlew test
          else
            echo "❌ No recognized build file found (pom.xml or build.gradle)."
            exit 1
          fi
